// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybakztvlzrfoayybtyvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliYWt6dHZsenJmb2F5eWJ0eXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODA0MDksImV4cCI6MjA3Mzg1NjQwOX0.AAyZnmiQWNbM3u4yCEZMyn7pPSi5icGDWov36q5Wp_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});